balena-os/balena-odroid

- CHANGELOG.md
- layers/meta-resin-odroid/conf/layer.conf
- layers/meta-resin-odroid/conf/samples/bblayers.conf.sample
- odroid-c1.coffee
- odroid-ux3.coffee
@agherzan @floion
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-odroid/2)
> Transition to jethro

- CHANGELOG.md
- odroid-c1.coffee
- odroid-ux3.coffee
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-odroid/3)
> Promote boards to released

- .gitmodules
- layers/meta-resin-odroid/conf/samples/bblayers.conf.sample
> Switch to docker

- CHANGELOG.md
- layers/meta-resin-odroid/conf/samples/local.conf.sample
> Improve build disk usage

- CHANGELOG.md
- layers/meta-resin-odroid/recipes-containers/docker-disk/docker-resin-supervisor-disk.bbappend
Connects to resin-os/meta-resin#133-supervisor-custom-image-tag
@telphan @floion
> Custom docker images in connectable builds on resin-odroid

- CHANGELOG.md
- layers/meta-resin-odroid/conf/samples/local.conf.sample
Connects to resin-os/meta-resin#137-replace-SUPERVISOR-TAG
@telphan @floion @petrosagg
> Replace SUPERVISOR_TAG by TARGET_TAG on resin-odroid

- CHANGELOG.md
- layers/meta-resin-odroid/conf/samples/local.conf.sample
Connects to resin-os/meta-resin#128-debug-image
@telphan @floion @petrosagg
> Replace RESIN_STAGING_BUILD by DEBUG_IMAGE on resin-odroid

- .gitmodules
- odroid-c1.coffee
- odroid-ux3.coffee
This implements resin-os/resin-yocto-scripts#31
Signed-off-by: Eugene Mirotin eugene@resin.io
@agherzan @floion
> Update to use the simplified JSON building process on resin-odroid

- CHANGELOG.md
- odroid-c1.coffee
- odroid-ux3.coffee
> Switch partition with conf in coffee

- CHANGELOG.md
- layers/meta-resin-odroid/conf/samples/local.conf.sample
@agherzan @floion 
Connects to resin-os/meta-resin#315
> Replace DEBUG_IMAGE with DEVELOPMENT_IMAGE

- CHANGELOG.md
- layers/meta-resin-odroid/conf/samples/bblayers.conf.sample
Connects to resin-os/meta-resin#404-meta-fs-layer
@telphan @floion @petrosagg @petrosagg @michal-mazurek
> Add meta-filesystem as we need aufs-utils on resin-odroid

- README.md
Connects to contributing
@telphan @floion @michal-mazurek
> Add Contributing section on resin-odroid

- CHANGELOG.md
> * Update resin-yocto-scripts to fix logging in container builds on resin-odroid

- CHANGELOG.md
Fix the 1.X build with the latest Jenkins configuration.
> Update build scripts on 1.X branch

- CHANGELOG.md
- odroid-c1.coffee
Signed-off-by: Florin Sarbu <florin@resin.io>
> odroid-c1.coffee: Update yocto version to correct one

- CHANGELOG.md
- layers/meta-resin-odroid/conf/samples/bblayers.conf.sample
Signed-off-by: Florin Sarbu <florin@resin.io>
> bblayers.conf.sample: Update for Yocto Pyro

- CHANGELOG.md
- layers/meta-resin-odroid/recipes-support/hostapp-update-hooks/files/99-flash-bootloader
Signed-off-by: Florin Sarbu <florin@resin.io>
> hostapp-update-hooks: Fix 99-flash-bootloader bootloader md5sum check

- CHANGELOG.md
- layers/meta-resin-odroid/recipes-kernel/linux/linux-stable_%.bbappend
Customer requested this kernel module in the rootfs
Signed-off-by: Florin Sarbu <florin@resin.io>
> linux-stable_%.bbappend: Add uvcvideo.ko

- layers/meta-resin-odroid/recipes-bsp/u-boot-hardkernel/u-boot-hardkernel/0001-odroid-c1-Enable-CONFIG_CMD_SETEXPR.patch
- layers/meta-resin-odroid/recipes-bsp/u-boot-hardkernel/u-boot-hardkernel_2011.03.bbappend
- layers/meta-resin-odroid/recipes-bsp/u-boot/files/0001-odroid-xu4-Enable-CONFIG_CMD_SETEXPR.patch
- layers/meta-resin-odroid/recipes-bsp/u-boot/u-boot_%.bbappend
This fixes https://github.com/balena-os/balena-odroid/issues/103
> Added CONFIG_CMD_SETEXPR for odroid-c1 and odroid-xu4

- layers/meta-balena-odroid/recipes-bsp/u-boot-hardkernel/u-boot-hardkernel_2011.03.bbappend
- layers/meta-balena-odroid/recipes-kernel/linux/linux-hardkernel/0001-tools-Add-Build.include-script.patch
- layers/meta-balena-odroid/recipes-kernel/linux/linux-hardkernel_%.bbappend
Update meta-balena from 2.38.3 to 2.43.0
Changelog-entry: Update the meta-balena submodule from v2.38.3 to v2.43.0
Signed-off-by: Florin Sarbu <florin@balena.io>
> layers/meta-balena: Update meta-balena to v2.43.0

- odroid-c1.coffee
- odroid-xu4.coffee
Changelog-entry: Set private to false in .coffee files for the public device types
Signed-off-by: Florin Sarbu <florin@balena.io>
> .coffee: Set private to false for the public device types

- odroid-c1.coffee
- odroid-xu4.coffee
Updating getting started links from resin.io to balena.io.
One commit per file changed and a single changelog entry.
> Updating getting started links
